stages:
    - test
    - build

variables:
    DOCKER_IMAGE_NAME: cronology:api-2.0.0

tests-job:
    image: node:22.15.0-alpine3.21
    stage: test
    script:
        - npm install
        - npx tsc
        - node ./dist/api cli-env-set dev
        - npm run test

build-job:
    image: docker:28.1.1-cli
    stage: build
    script:
        - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        - docker build -t $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME .
        - docker push $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME